local_cpu: False
max_local_cpu_size: 0
#local_disk:
max_local_disk_size: 0
remote_serde: NULL

enable_nixl: True
nixl_role: "receiver"
nixl_receiver_host: "10.20.11.2"
nixl_receiver_port: 55555
nixl_peer_init_port: 7300
nixl_peer_alloc_port: 7400
nixl_buffer_size: 1798963200 # 2GB
nixl_buffer_device: "cuda"
nixl_backends: [UCX]
nixl_enable_gc: True