local_cpu: False
max_local_cpu_size: 0
#local_disk:
max_local_disk_size: 0
remote_serde: NULL

enable_nixl: True
enable_xpyd: True
nixl_role: "sender"
nixl_proxy_host: "10.20.10.2"
nixl_proxy_port: 7500
nixl_buffer_size: 1798963200 # 1.6GB
nixl_buffer_device: "cuda"


# page size: 17568KB * 100 